Fix monitor metric issue
BirkhoffG/cfnet pull request #40
Opened 2022-10-14 03:00 UTC by Grahams-Uncle

2022-10-14 03:03 UTC, Grahams-Uncle commented
fix #40

2022-10-14 03:03 UTC, BirkhoffG requested changes

2022-10-14 03:03 UTC, BirkhoffG commented on cfnet/_ckpt_manager.py
> +            raise ValueError('The monitor_metrics is not appropriately configured.')
Change to 
'''python
"The monitor_metrics (`{}`) is not appropriately configured.".format(self.monitor_metrics)
'''

2022-10-16 16:38 UTC, BirkhoffG approved these changes

2022-10-16 16:38 UTC, merged