Add Visualization
BirkhoffG/cfnet pull request #77
Opened 2022-12-20 05:25 UTC by Grahams-Uncle

2022-12-20 18:34 UTC, BirkhoffG requested changes
I would suggest to reduce the arguments passed, perhaps just passing `evaluate.Explanation` would be a better choice. 

I also think too many arguments in the plotting functions. We should keep these arguments, but we need to provide default arguments so that users will not be overwhelmed when they use this framework.

For example, I would refactor `swarmplot` into
```python
def swarmplot(
    cf_exp: Explanation,
    plot_name: str = "Swarm Plot",  # The name for the plot
    sample_num: int = 100,  # The number of sample for the plot
    seed: int = 42,  # Seed for PRG for random sampling
    separate_class: bool = True, # Whether to separate the data based on the classifier result
):
    ...
```

`X`, `cfs`, `dm`, `pred_fn` are contained in `Explanation`.

You can keep your current code, except making your current function into a private function (e.g., you can just name `swarmplot` as `_swarmplot`), and write a wrapper `swarmplot` to call this private `_swarmplot` function.

2022-12-21 22:52 UTC, Grahams-Uncle commented
fix #34

2022-12-23 01:44 UTC, BirkhoffG requested changes

2022-12-23 01:44 UTC, BirkhoffG commented on nbs/ipynb_path.py
> +sys.path.append('../../../Downloads/cfnet-master-2')
Don't change this file!

2022-12-24 23:23 UTC, Grahams-Uncle commented on cfnet/plotting.py
> +
Which function needs an explanation?

2022-12-26 23:12 UTC, BirkhoffG approved these changes

2022-12-27 00:43 UTC, merged